name: CI

on:
  push:
    branches:
      - master

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install depedencies
      run: yarn install
    - name: Test
      run: yarn test
